include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    public_member_api_docs: false
    eol_at_end_of_file: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    discarded_futures: false
    avoid_catching_errors: false
    avoid_catches_without_on_clauses: false
    avoid_positional_boolean_parameters: false

analyzer:
  exclude:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
